/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 06-Jul-2021 14:49:52
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 21
 * Denominator Length  : 21
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2021a/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int Nb = 21;
const real32_T bn[21] = {
  2.500868845e-09,5.001737691e-08,4.751650806e-07,2.850990541e-06,1.211670951e-05,
  3.877347262e-05, 9.69336761e-05,0.0001938673522, 0.000315034471,0.0004200459516,
  0.0004620505497,0.0004200459516, 0.000315034471,0.0001938673522, 9.69336761e-05,
  3.877347262e-05,1.211670951e-05,2.850990541e-06,4.751650806e-07,5.001737691e-08,
  2.500868845e-09
};
const int Na = 21;
const real32_T an[21] = {
                1,   -7.993788242,    32.24776459,   -86.15267181,    169.6131592,
     -260.1393127,    321.1838989,   -325.8437195,    275.1584473,    -194.898468,
      116.2181015,   -58.35420609,    24.59604073,    -8.64527607,    2.506714106,
    -0.5898103118,   0.1098868176, -0.01561185438, 0.001590100699,-0.0001034620072,
  3.232560175e-06
};
